import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { DesignTokens, Subject } from '@/types'
import { generateLandingHTML } from '@/lib/generators/landing'
import { renderSocialTemplate, SOCIAL_FORMATS } from '@/lib/generators/social'
import { renderWallpaper, WALLPAPER_STYLES } from '@/lib/generators/wallpaper'
import { getLaptopSVG, getIPhoneSVG } from '@/lib/generators/mockup'
import { tokensToCSS, tokensToJSON } from '@/lib/tokens'

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise(res => canvas.toBlob(b => res(b!), 'image/png'))
}

function makeLandingScreenshot(tokens: DesignTokens): string {
  const canvas = document.createElement('canvas')
  canvas.width = 1280
  canvas.height = 800
  const ctx = canvas.getContext('2d')!

  const bg = ctx.createLinearGradient(0, 0, 1280, 800)
  bg.addColorStop(0, tokens.colors.bg)
  bg.addColorStop(1, tokens.colors.surface)
  ctx.fillStyle = bg
  ctx.fillRect(0, 0, 1280, 800)

  const blob = ctx.createRadialGradient(900, 350, 0, 900, 350, 500)
  blob.addColorStop(0, tokens.colors.accent + 'aa')
  blob.addColorStop(1, 'transparent')
  ctx.fillStyle = blob
  ctx.fillRect(0, 0, 1280, 800)

  ctx.fillStyle = tokens.colors.text
  ctx.font = '700 68px serif'
  ctx.fillText('Design that', 80, 280)
  ctx.fillStyle = tokens.colors.accent
  ctx.fillText('inspires.', 80, 365)

  return canvas.toDataURL('image/png')
}

export async function exportAllZip(
  tokens: DesignTokens,
  imageEl: HTMLImageElement | null,
  subjects: Subject[] = []
): Promise<void> {
  const zip = new JSZip()

  // Root files
  zip.file('tokens.json', tokensToJSON(tokens))
  zip.file('styles.css', tokensToCSS(tokens))

  // README
  zip.file(
    'README.md',
    `# InspoKit Export

Generated by InspoKit — https://inspokit.app

## Contents

- \`tokens.json\` — Design tokens (colors, radii, shadows, fonts)
- \`styles.css\` — CSS custom properties
- \`landing/\` — 3 HTML landing page templates
- \`social/\` — Social media templates (PNG)
- \`wallpapers/\` — iPhone wallpapers at 1290×2796 (PNG)
- \`mockups/\` — Device mockup frames (SVG)

## Usage

Open any \`.html\` file directly in a browser. The CSS variables are pre-populated with your palette.

To customize, edit \`styles.css\` and link it to the HTML files.
`
  )

  // Landing pages
  const landingFolder = zip.folder('landing')!
  for (const tpl of ['hero-left', 'centered', 'split'] as const) {
    landingFolder.file(`${tpl}.html`, generateLandingHTML(tpl, tokens, subjects))
  }

  // Social templates
  const socialFolder = zip.folder('social')!
  for (const fmt of SOCIAL_FORMATS) {
    const canvas = document.createElement('canvas')
    renderSocialTemplate(canvas, fmt, tokens, subjects)
    socialFolder.file(`${fmt}.png`, await canvasToBlob(canvas))
  }

  // Wallpapers
  const wallFolder = zip.folder('wallpapers')!
  for (const { id } of WALLPAPER_STYLES) {
    const canvas = document.createElement('canvas')
    renderWallpaper(canvas, id, tokens, imageEl ?? undefined)
    wallFolder.file(`wallpaper-${id}.png`, await canvasToBlob(canvas))
  }

  // Mockups
  const mockupFolder = zip.folder('mockups')!
  const screenshotUrl = makeLandingScreenshot(tokens)

  const phoneCanvas = document.createElement('canvas')
  renderWallpaper(phoneCanvas, 'mesh', tokens)
  const phoneUrl = phoneCanvas.toDataURL('image/png')

  mockupFolder.file('mockup-laptop.svg', getLaptopSVG(screenshotUrl))
  mockupFolder.file('mockup-iphone.svg', getIPhoneSVG(phoneUrl))

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
  saveAs(blob, 'inspokit-export.zip')
}
